var firstName;
firstName = "Emily";
var lastName;
lastName = "Richter";
var age;
age = "23";
var street;
street = "42 Wallaby Way";
var city;
city = "Sydney";
var zipCode;
zipCode = "34567";
console.log(firstName);
console.log(lastName);
console.log(age);
console.log(street);
console.log(city);
console.log(zipCode);